In [2]:
import pandas as pd
from pandas import read_csv

In [3]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [5]:
data=read_csv("/content/drive/My Drive/dataset/penjualan_tiket.csv")
print(data)

   tanggal_film judul_film  ... tiket_terjual  harga_tiket
0      1/1/2010        aku  ...           9.0      50000.0
1      8/3/2011       kamu  ...          20.0     100000.0
2      4/9/2011        dia  ...          15.0      20000.0
3      1/1/2010        aku  ...           9.0      50000.0
4     2/13/2013        NaN  ...          35.0       5000.0
5    12/10/2011       laki  ...          55.0      25000.0
6    17/10/2012      cewek  ...          56.0      30000.0
7    31/01/2011      jalan  ...           5.0      15000.0
8     10/1/2012      kipas  ...          19.0      30000.0
9           NaN        NaN  ...           NaN          NaN
10          NaN        NaN  ...           NaN          NaN
11          NaN        NaN  ...           NaN          NaN
12          NaN        NaN  ...           NaN          NaN
13          NaN        NaN  ...           NaN          NaN
14          NaN        NaN  ...           NaN          NaN
15          NaN        NaN  ...           NaN          NaN

[16 rows x 6 columns]

In [21]:
data.dropna() #menghapus data kosong

  tanggal_film judul_film  ... tiket_terjual  harga_tiket
0     1/1/2010        aku  ...           9.0      50000.0
1     8/3/2011       kamu  ...          20.0     100000.0
2     4/9/2011        dia  ...          15.0      20000.0
3     1/1/2010        aku  ...           9.0      50000.0
5   12/10/2011       laki  ...          55.0      25000.0
6   17/10/2012      cewek  ...          56.0      30000.0
7   31/01/2011      jalan  ...           5.0      15000.0
8    10/1/2012      kipas  ...          19.0      30000.0

[8 rows x 6 columns]

In [25]:
data.drop_duplicates(subset="tanggal_film", keep=False) #menghapus data duplikat

  tanggal_film judul_film  ... tiket_terjual  harga_tiket
1     8/3/2011       kamu  ...          20.0     100000.0
2     4/9/2011        dia  ...          15.0      20000.0
4    2/13/2013        NaN  ...          35.0       5000.0
5   12/10/2011       laki  ...          55.0      25000.0
6   17/10/2012      cewek  ...          56.0      30000.0
7   31/01/2011      jalan  ...           5.0      15000.0
8    10/1/2012      kipas  ...          19.0      30000.0

[7 rows x 6 columns]